export const data =[
    {
        id:'1',
        Region:'Yunga',
        Localidad:'Valle Grande',
        Lugar: 'Selva San Fransico',
        Tiempo: '8',
        Guia: 'Amir Sumaqmi',
        Precio: '20.000',
        Favorito: false,
        Calificacion: 5.0,
        Images: require('../../assets/8.png'),
        ImgGuia: require('../../assets/amir.png')
    },
    {
        id:'2',
        Region:'Yunga',
        Localidad:'Valle Grande',
        Lugar: 'Selva San Fransico',
        Tiempo: '10',
        Guia: 'Veronica Perez',
        Precio: '23.000',
        Favorito: false,
        Calificacion: 5.0,
        Images: require('../../assets/6.png'),
        ImgGuia: require('../../assets/veronica.png')
        
    },
    {
        id:'3',
        Region:'Yunga',
        Localidad:'Valle Grande',
        Lugar: 'Selva San Fransico',
        Tiempo: '6',
        Guia: 'Miguel Vicente',
        Precio: '10.000',
        Favorito: true,
        Calificacion: 3.9,
        Images:require('../../assets/8.png'),
        ImgGuia: require('../../assets/miguel.png')
    },
    {
        id:'4',
        Region:'Yunga',
        Localidad:'Valle Grande',
        Lugar: 'Selva San Fransico',
        Tiempo: '8',
        Guia: 'Eli Erizariaga',
        Precio: '12.000',
        Favorito: false,
        Calificacion: 4.8,
        Images:require('../../assets/5.png'),
        ImgGuia: require('../../assets/eli.png')
    },
    {
        id:'5',
        Region:'Yunga',
        Localidad:'Villa Monte',
        Lugar: 'Eco Portal de piedra',
        Tiempo: '8',
        Guia: 'Mirta juarez',
        Precio: '12.000',
        Favorito: true,
        Calificacion: 4.8,
        Images: require('../../assets/9.png'),
        ImgGuia: require('../../assets/juarez.png')
    },
    {
        id:'6',
        Region:'Yunga',
        Localidad:'Valle Grande',
        Lugar: 'Valle Colorado',
        Tiempo: '8',
        Guia: 'Marcelino Piñero',
        Precio: '18.000',
        Favorito: false,
        Calificacion: 4.9,
        Images: require('../../assets/3.png'),
        ImgGuia: require('../../assets/marcelino.png')
    },
    {
        id:'7',
        Region:'Yunga',
        Localidad:'San Francisco',
        Lugar: 'Libertador Gral. San Martin',
        Tiempo: '9',
        Guia: 'Miguel Vicente',
        Precio: '15.000',
        Favorito: true,
        Calificacion: 3.8,
        Images:require('../../assets/4.png'),        
        ImgGuia: require('../../assets/miguel.png')
    },
]