export { AmountSelector } from "./AmountSelector/AmountSelector";
export { ComentarioContent } from "./ComentarioContent/ComentarioContent";
export { DetalleContent } from "./DetalleContent/DetalleContent";
export { GeneralContent } from "./RecorridoDetails/GeneralContent/GeneralContent";
export { ModalInfo } from "./ModalInfo/ModalInfo";
export { RecorridoCard } from "./RecorridoCard/RecorridoCard";
export { RecorridoCardVertical } from "./RecorridoCard/RecorridoCardVertical";
// export { RecorridoList } from "./RecorridoList/RecorridoList";
export { SearchBar } from "./SearchBar/SearchBar";
export { TimeSelector } from "./TimeSelector/TimeSelector";
